# Generated by Django 5.1.2 on 2024-11-04 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraicreds_name_keys_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraicreds',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_creds', to=settings.AUTH_USER_MODEL),
        ),
    ]
