# Generated by Django 5.1.2 on 2024-11-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_useraicreds_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraicreds',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
